### ISSUE TITLE
Export API

### ISSUE THREAD

**Issue by fishouttah20** [cudeso/censys-certif-crawl#1]
Have you considered using the Export API which doesn't have the limits of the Index API? You'd need to download the results as json/csv and then import into the database.

**Comment by cudeso** [comment]
I totally overlooked the Export API; that might have been a better solution. Thanks for suggesting this!

**Comment by fishouttah20** [comment]
No worries, thanks for sharing your code! Even with the API speed limitations it was still very helpful for some cert/domain recon.
